### PR TITLE
Change logic to of fs_unmount

### PR DESCRIPTION
**Pull request by Wangzijun**
Change logic to be more understandable

### CODE REVIEW

**Comment by Awesome-HarmonyOS** [comment]
Is there any difference?

**Comment by tsrjchenhai** [comment]
I'm checking. I'm not sure yet.



tsrjchenhai@126.com
 
From: Awesome-HarmonyOS
Date: 2019-08-13 15:47
To: Awesome-HarmonyOS/HarmonyOS
CC: Subscribed
Subject: Re: [Awesome-HarmonyOS/HarmonyOS] Change logic to of fs_unmount (#80)
Is there any difference?

**Comment by Wangzijun** [comment]
there is no difference, but code becoming more clear and more understandable.

**Comment by abrahamgreyson** [comment]
@Wangzijun 这部分代码是复制的 liteOS， 你可以直接进 liteOS 发 pr。
这个仓库的主人，让你误以为它和官方仓库有什么关系。你给他发 pr，它也不敢合并，直接点说，他也没有任何资历合并

**Comment by flying-yes** [comment]
您好！    邮件已收到，我会尽快给您回复。。。

**Pull request closed without merging**
